name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    
    - name: Extract version from tag
      id: version
      run: |
        $VERSION = $env:GITHUB_REF -replace 'refs/tags/v', ''
        echo "VERSION=$VERSION" >> $env:GITHUB_OUTPUT
      shell: pwsh
    
    - name: Restore dependencies
      run: dotnet restore src/MyPhotoHelper.sln
    
    - name: Build and create Squirrel package
      run: |
        .\build-squirrel.ps1 -Version ${{ steps.version.outputs.VERSION }} -ReleaseNotes "See release notes on GitHub"
      shell: pwsh
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        files: |
          ./Releases/Setup.exe
          ./Releases/RELEASES
          ./Releases/MyPhotoHelper-${{ steps.version.outputs.VERSION }}-full.nupkg
        body: |
          ## Release v${{ steps.version.outputs.VERSION }}
          
          ### What's New
          - Flexible settings system with key-value architecture
          - Fixed all build errors and improved stability
          - Enhanced database management tools
          - Improved Settings page functionality
          
          ### Installation
          - Download `Setup.exe` below to install MyPhotoHelper
          - The application will automatically check for updates
          
          ### Notes
          - AI features are temporarily disabled during system upgrade
          - Core photo management features remain fully functional
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}